import type { Anime } from '@tutkli/jikan-ts/types';

export type SavedAnimeEntry = Pick<
  Anime,
  | 'mal_id'
  | 'url'
  | 'images'
  | 'trailer'
  | 'titles'
  | 'title'
  | 'title_english'
  | 'title_japanese'
  | 'title_synonyms'
  | 'type'
  | 'source'
  | 'episodes'
  | 'status'
  | 'airing'
  | 'aired'
  | 'duration'
  | 'rating'
  | 'score'
  | 'scored_by'
  | 'rank'
  | 'popularity'
  | 'members'
  | 'favorites'
  | 'synopsis'
  | 'background'
  | 'season'
  | 'year'
  | 'producers'
  | 'studios'
  | 'genres'
  | 'explicit_genres'
  | 'streaming'
>;
